name: CI
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    if: github.actor != 'shopify[bot]'
    steps:
      - uses: actions/checkout@v4
      - name: Lighthouse
        uses: shopify/lighthouse-ci-action@v1
        with:
          store: ${{ vars.SHOP_STORE }}
          access_token: ${{ secrets.SHOP_ACCESS_TOKEN }}
          collection_handle: ${{ vars.COLLECTION_HANDLE }}
          product_handle: ${{ vars.PRODUCT_HANDLE }}
          password: ${{ secrets.SHOP_PASSWORD }}
          lhci_github_app_token: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          lhci_min_score_performance: 0.8
          lhci_min_score_accessibility: 0.8

  theme-check:
    name: Theme Check
    runs-on: ubuntu-latest
    permissions: write-all
    if: github.actor != 'shopify[bot]'
    steps:
      - uses: actions/checkout@v4
      - name: Theme Check
        uses: shopify/theme-check-action@v2
        with:
          token: ${{ github.token }}
